### ISSUE TITLE
usage of non-root user for container and generated outputs

### ISSUE THREAD

**Issue by e-skulk** [Bleala/Vdirsyncer-DOCKERIZED#4]
Hi,

The application inside container seems to run as root user. All generated output files (e.g., ics calendar files) are owned by the user root. 
Would it be possible to change to a non-root user?

Best practice is to define the user and group as an environment variable for the Vdirsyncer container (as far I know).

Would be great to have this option, because another program cannot use the ics file because he is not root (and setting the file permission once does not help).

Thanks for _dockerizing_ it.

**Comment by Bleala** [comment]
Hello there!

Yes it‘s running as root, because i did not care about this to be honest, did not need it by myself, that the files are accessible to other users, because i use a docker volume.

But i‘ll add an option, that you can set the user through an environment variable 😉

Hope i am able to do this during this weekend!

Greetings

**Comment by Bleala** [comment]
Hello again!

Your problem should be solved with the following [Release](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/releases/tag/2.3.0) 😄 

I'll close this issue, hope everything is fine for you now!

Have a nice weekend!
